version: '3'

services:
  mongo:
    image: mongo:3.6.2
    ports: 
      - "27017:27017"
    restart: always

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    command: node index.js